server:
  port: 8080

spring:
  application:
    name: book-service

logging:
  level:
    org.flywaydb.core.internal.license: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
